### PR TITLE
[Bugfix] Fix sysfolder workaround with dbal

### PR DESCRIPTION
**Pull request by Smove**
Typo3 uses the dbal syntax since v8.4

### CODE REVIEW

**Comment by dmitryd** [comment]
1. What does it fix?
1. It cannot be merged due to wrong formatting of the code.

**Comment by Smove** [comment]
Currently pages doesn't get into sitemap if they are in a sysfolder, the old workaround does not work since dbal is used in core because of the different sql syntax.

I will redo formatting again tomorrow

**Comment by Smove** [comment]
Formatting should be correct now.

**Comment by Smove** [comment]
Any update on this PR?

**Comment by echavaillaz** [comment]
Please merge this. It solve my issue : https://github.com/dmitryd/typo3-dd_googlesitemap/issues/89

Thanks!

**Comment by dmitryd** [comment]
Thanks!

**Pull request merged**
