### PR TITLE
TCA in ext_tables.php

### PR DESCRIPTION
**Pull request by SvenJuergens**
Hello Dmitry,

There is this Breaking Change in TYPO3 8:  [Breaking: # 78384 - Frontend Ignores TCA in ext_tables.php](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Breaking-78384-FrontendIgnoresTCAInExtTables.html)
That's why I moved the content.
It is still compatible with version TYPO3 6.2.1 (unfortunately I could not find a 6.2.0 anymore) and compatible with PHP 5.3.14 (5.3.2 I could not find the fast one here either).

### CODE REVIEW

**Comment by SvenJuergens** [comment]
Hi, @davidlemaitre thanks for the feedback. i fixed the typo.
At the moment dd_googlesitemap still support TYPO3 6.2.0 and this version of TYPO3 support PHP 5.3.7. but the short array syntax was added in PHP 5.4.0 ...

**Comment by w010** [comment]
Maybe it should now stop being compatible with 6.2, when is a 9.x about to be released in a moment?

**Comment by SvenJuergens** [comment]
hi @w010, I see it that way too, but that must decide @dmitryd

**Comment by dmitryd** [comment]
Thank you for help in solving this :) Finally I had time to work on this ext again and the change is merged! 🥤

**Pull request merged**
