### PR TITLE
[TASK] Log errors on sitemap eID URL request

### LINKED ISSUE #71: Log errors on sitemap eID URL request
If an error occurs within the Scheduler task when requesting a sitemap eID URL, there is no report and message about this at all.

The method `GeneralUtility::getUrl()` supports a `$report` parameter for this case which should be used to show error details to the user. The full report should be logged.

### PR DESCRIPTION
**Pull request by mbrodala**
This logs errors when requesting eID URLs and also displays a flash message in the TYPO3 scheduler.

Fixes #71

### CODE REVIEW

**Comment by dmitryd** [comment]
Not sure if it is a good idea. What if the scheduler job runs very often (every 5 mins, for example)? It can flood the Backend with messages. I sometimes see such extensions: you open the BE and see a long list of flash messages going down. This does not look nice at all.

**Comment by mbrodala** [comment]
That wouldn't be a problem here since this flash message is not stored in the session. Thus you'll see only a single flash message upon manual execution in the backend.

**Comment by h3nn3s** [comment]
After testing, it looks good for me. 
Since flash messages are not stored in the session, its a nice solution for debuggin (when scheduler is executed manually).

**Comment by dmitryd** [comment]
Thank you.

**Pull request merged**
