### PR TITLE
[FEATURE] change frequency can be set manually in ther page record 

### PR DESCRIPTION
**Pull request by hannesbochmann**

### CODE REVIEW

**Comment by hannesbochmann** [comment]
I wanted to update the manual but I have no editor which can still save .sxw files. Could you change the line "calculates page change frequency based on history of page updates" e.g. to "calculates page change frequency based on history of page updates as long as the change frequency is not set manually in the page record"

**Comment by dmitryd** [comment]
OpenOffice or LibreOffice edits sxw files :)

**Comment by hannesbochmann** [comment]
I can edit it with LibreOffice but I can't save it anymore as sxw.

**Comment by hannesbochmann** [comment]
push

**Comment by hannesbochmann** [comment]
ping

**Comment by dmitryd** [comment]
Planned for the next release :)

**Pull request merged**
