### PR TITLE
[FEATURE] Generate sitemaps for different domains (e.g. web and mobil)

### PR DESCRIPTION
**Pull request by felixsemmler**
This feature is related to https://github.com/dmitryd/typo3-dd_googlesitemap/issues/34. I adapted it to version 2.x of typo3-dd_googlesitemap and fixed the things you mentioned (unescaped HTML (possible XSS) and unescaped submitted data is passed to the database (possible SQL injection)).

### CODE REVIEW

**Comment by vdespa** [comment]
@dmitryd This is a nice addition to the current functionality. Would it be possible to merge the PR into your code?

**Comment by dmitryd** [comment]
I'll need time to look at it. Currently there is a lot of load at work and mot much time for free exts. But as soon as I got spare minutes, I will definitely look at it!

**Comment by dmitryd** [comment]
A change will be needed: multiple domain records should be selectable.

One problem to solve: dev/stage/live handling with domain records.

**Comment by dmitryd** [comment]
I thought about it and I propose to make a separate extension from it. The reason is that it will break existing installations. Now when people update extensions with composer, they can suddenly loose their existing configurations.

The best way would be to have a separate scheduler task for this in a separate extension.

**Pull request closed without merging**
