### PR TITLE
[TASK] Add typo3/cms extension-key to composer.json

### PR DESCRIPTION
**Pull request by t3easy**
See: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#minimal-composer-json

### CODE REVIEW

**Comment by t3easy** [comment]
This is not just an task, it's an urgent bugfix because it is installed in the folder typo3_dd_googlesitemap now!
image

**Comment by dmitryd** [comment]
@t3easy I believe you need a newer version of composer installers. They take care of it.

**Comment by t3easy** [comment]
It's an TYPO3 8.7 with all latest packages.

**Comment by dmitryd** [comment]
Strange. We still run sites on 8.7, updated to ELTSes and have no issues.

**Comment by t3easy** [comment]
If you don't set the extension-key option, the typo3/cms-composer-installers normalizes the composer package name so dash will be underscore. But if the packages has an other name like here, it needs the extension-key property.

**Comment by t3easy** [comment]
> Strange. We still run sites on 8.7, updated to ELTSes and have no issues.

Did you updated dd_googlesitemap to 2.3.1?
On 2.2.0 it was ok because of the deprecated https://github.com/dmitryd/typo3-dd_googlesitemap/commit/e11ab8e3362bdedf428c1c57b1969f8607a6578b#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L25

**Comment by dmitryd** [comment]
Ok, let's merge it

**Comment by t3easy** [comment]
> Ok, let's merge it

Thank you! Please also create a 2.3.2 release to have a stable installable version.

**Comment by dmitryd** [comment]
Release is done.

**Comment by t3easy** [comment]
Thanks!

**Pull request merged**
